# Generated by Django 5.2.1 on 2025-05-28 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('property_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(default='Mango', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('planting_date', models.DateField()),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='surveillance.grower')),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveillance_date', models.DateTimeField()),
                ('pest_or_disease', models.CharField(max_length=100)),
                ('plant_part', models.CharField(choices=[('leaves', 'Leaves'), ('fruit', 'Fruit'), ('stem', 'Stem'), ('roots', 'Roots')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='surveillance.plant')),
            ],
        ),
    ]
